<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Pim4xFI' shared service.

return $this->privates['.service_locator.Pim4xFI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'data' => ['privates', '.errored..service_locator.Pim4xFI.App\\Entity\\User', NULL, 'Cannot autowire service "api_platform.subresource_operation_factory.cached.inner": it references class "App\\Entity\\User" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'panierRepository' => ['privates', 'App\\Repository\\PanierRepository', 'getPanierRepositoryService.php', true],
    'product' => ['privates', '.errored..service_locator.Pim4xFI.App\\Entity\\Product', NULL, 'Cannot autowire service "api_platform.subresource_operation_factory.cached.inner": it references class "App\\Entity\\Product" but no such service exists.'],
], [
    'data' => 'App\\Entity\\User',
    'manager' => '?',
    'panierRepository' => 'App\\Repository\\PanierRepository',
    'product' => 'App\\Entity\\Product',
]);
