<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.NS74uXT' shared service.

return $this->privates['.service_locator.NS74uXT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\FillProductId::__invoke' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\GetProductCategory::__invoke' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\GetProductId::__invoke' => ['privates', '.service_locator.UfAGkL9', 'get_ServiceLocator_UfAGkL9Service.php', true],
    'App\\Controller\\GetSubProductCategory::__invoke' => ['privates', '.service_locator.4UxnGZb', 'get_ServiceLocator_4UxnGZbService.php', true],
    'App\\Controller\\GetUserPanier::__invoke' => ['privates', '.service_locator.Pim4xFI', 'get_ServiceLocator_Pim4xFIService.php', true],
    'App\\Controller\\LoginUser::__invoke' => ['privates', '.service_locator.Dc7.syx', 'get_ServiceLocator_Dc7_SyxService.php', true],
    'App\\Controller\\PostUser::__invoke' => ['privates', '.service_locator.n50uYTI', 'get_ServiceLocator_N50uYTIService.php', true],
    'App\\Controller\\ValidateUserPanier::__invoke' => ['privates', '.service_locator.SFe7.59', 'get_ServiceLocator_SFe7_59Service.php', true],
    'App\\Controller\\FillProductId:__invoke' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\FillProductId' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\GetProductCategory:__invoke' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\GetProductCategory' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\GetProductId:__invoke' => ['privates', '.service_locator.UfAGkL9', 'get_ServiceLocator_UfAGkL9Service.php', true],
    'App\\Controller\\GetProductId' => ['privates', '.service_locator.UfAGkL9', 'get_ServiceLocator_UfAGkL9Service.php', true],
    'App\\Controller\\GetSubProductCategory:__invoke' => ['privates', '.service_locator.4UxnGZb', 'get_ServiceLocator_4UxnGZbService.php', true],
    'App\\Controller\\GetSubProductCategory' => ['privates', '.service_locator.4UxnGZb', 'get_ServiceLocator_4UxnGZbService.php', true],
    'App\\Controller\\GetUserPanier:__invoke' => ['privates', '.service_locator.Pim4xFI', 'get_ServiceLocator_Pim4xFIService.php', true],
    'App\\Controller\\GetUserPanier' => ['privates', '.service_locator.Pim4xFI', 'get_ServiceLocator_Pim4xFIService.php', true],
    'App\\Controller\\LoginUser:__invoke' => ['privates', '.service_locator.Dc7.syx', 'get_ServiceLocator_Dc7_SyxService.php', true],
    'App\\Controller\\LoginUser' => ['privates', '.service_locator.Dc7.syx', 'get_ServiceLocator_Dc7_SyxService.php', true],
    'App\\Controller\\PostUser:__invoke' => ['privates', '.service_locator.n50uYTI', 'get_ServiceLocator_N50uYTIService.php', true],
    'App\\Controller\\PostUser' => ['privates', '.service_locator.n50uYTI', 'get_ServiceLocator_N50uYTIService.php', true],
    'App\\Controller\\ValidateUserPanier:__invoke' => ['privates', '.service_locator.SFe7.59', 'get_ServiceLocator_SFe7_59Service.php', true],
    'App\\Controller\\ValidateUserPanier' => ['privates', '.service_locator.SFe7.59', 'get_ServiceLocator_SFe7_59Service.php', true],
], [
    'App\\Controller\\FillProductId::__invoke' => '?',
    'App\\Controller\\GetProductCategory::__invoke' => '?',
    'App\\Controller\\GetProductId::__invoke' => '?',
    'App\\Controller\\GetSubProductCategory::__invoke' => '?',
    'App\\Controller\\GetUserPanier::__invoke' => '?',
    'App\\Controller\\LoginUser::__invoke' => '?',
    'App\\Controller\\PostUser::__invoke' => '?',
    'App\\Controller\\ValidateUserPanier::__invoke' => '?',
    'App\\Controller\\FillProductId:__invoke' => '?',
    'App\\Controller\\FillProductId' => '?',
    'App\\Controller\\GetProductCategory:__invoke' => '?',
    'App\\Controller\\GetProductCategory' => '?',
    'App\\Controller\\GetProductId:__invoke' => '?',
    'App\\Controller\\GetProductId' => '?',
    'App\\Controller\\GetSubProductCategory:__invoke' => '?',
    'App\\Controller\\GetSubProductCategory' => '?',
    'App\\Controller\\GetUserPanier:__invoke' => '?',
    'App\\Controller\\GetUserPanier' => '?',
    'App\\Controller\\LoginUser:__invoke' => '?',
    'App\\Controller\\LoginUser' => '?',
    'App\\Controller\\PostUser:__invoke' => '?',
    'App\\Controller\\PostUser' => '?',
    'App\\Controller\\ValidateUserPanier:__invoke' => '?',
    'App\\Controller\\ValidateUserPanier' => '?',
]);
