<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.n50uYTI' shared service.

return $this->privates['.service_locator.n50uYTI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'data' => ['privates', '.errored..service_locator.n50uYTI.App\\Entity\\User', NULL, 'Cannot autowire service "api_platform.subresource_operation_factory.cached.inner": it references class "App\\Entity\\User" but no such service exists.'],
    'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
], [
    'data' => 'App\\Entity\\User',
    'encoder' => '?',
    'manager' => '?',
]);
