<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ltWRorf' shared service.

return $this->privates['.service_locator.ltWRorf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'data' => ['privates', '.errored..service_locator.ltWRorf.App\\Entity\\UserInfo', NULL, 'Cannot autowire service "api_platform.subresource_operation_factory.cached.inner": it references class "App\\Entity\\UserInfo" but no such service exists.'],
    'mailer' => ['services', 'swiftmailer.mailer.default', 'getSwiftmailer_Mailer_DefaultService.php', true],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
], [
    'data' => 'App\\Entity\\UserInfo',
    'mailer' => '?',
    'manager' => '?',
]);
