<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYNzTsIt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYNzTsIt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYNzTsIt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYNzTsIt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYNzTsIt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YNzTsIt',
    'container.build_id' => '1e1d7bce',
    'container.build_time' => 1563785491,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYNzTsIt');
